ignorePaths: []
dictionaryDefinitions:
  - name: 'obsidian-checklist'
    path: ./.cspell/obsidian-checklist.txt
    addWords: true
dictionaries:
  - 'obsidian-checklist'
words: []
ignoreWords: []
import: []
