ignorePaths: []
dictionaryDefinitions:
  - name: 'custom-dictionary'
    path: ./.cspell/custom-dictionary.txt
    addWords: true
dictionaries:
  - 'custom-dictionary'
words: []
ignoreWords: []
import: []
